dpkg:
 - cuda
 - cudnn
 - tensorrt
 - anydesk
 - teamviewer
 - qt5
 - qt6
 - ntp
 - ntpdate
 - ffmpeg
 - libyaml-cpp-dev
 - python3
 - python3.8
 - python3.10
 - htop
 - git
 - curl

pypi:
 - opencv-python
 - numpy
 - matplotlib
 - torch
 - torchvision
 - scikit-learn
 - pandas
 - Pillow
 - tensorrt
 - cupy
 - PyYAML
 - scipy
 - onnx
 - onnxruntime
 - onnxruntime-gpu
 - onnxsim
#  - beautifulsoup4
#  - Jinja2
 - Flask
 - cmake
 - tqdm
